### ISSUE TITLE
Geneseis 1:1 returning Exodus 1:1

### ISSUE THREAD

**Issue by jiachen247** [davewasmer/biblejs#3]
Books are not matching up.
Please fix thanks.

**Comment by jiachen247** [comment]
to String seems to print the book index plus one.

```
const Reference = require('biblejs').Reference;
var ref =new Reference("John 3:16");

console.log(ref.toString());
```
output : Acts 3:16

**Comment by sortofbusy** [comment]
@jiachen247 are you using version 0.0.8? I just checked and I'm getting the expected response.

**Comment by jiachen247** [comment]
The .toString() function does not work. I have tested this out with the code below. Output is as shown. It always shows the book index of +1

`var Reference = require('biblejs').Reference;
var refString = "Gen 3:16";

var ref = new Reference(refString);
console.log("This works ==> ");
console.log(ref);

console.log("this dosent!");
console.log("This dosent " + ref.toString());`

Output: 
![image](https://cloud.githubusercontent.com/assets/17170991/20486510/047128ca-b03b-11e6-96d6-35ecd1249cba.png)

**Comment by sortofbusy** [comment]
Thanks for providing the example code. The off-by-one problem is related to how data is stored in the Reference object vs accessed by the user, and I contributed a pull request last summer to fix this issue.
I have two questions: are you using version `0.8.0`? Also, are you installing with`npm` or `bower`? I think the `bower` version may not be fully updated.

**Comment by jiachen247** [comment]
@sortofbusy  Im currently using biblejs@0.0.8 from npm which dosent seem to be working.

**Comment by davewasmer** [comment]
Hey folks, sorry for the lack of support lately (this project fell down on the priority list). I just pushed an update though, now with test coverage, and this particular issue should be fixed! Let me know if you hit any snags.
